//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class parkinginfo {
    
    private parkinginfoItem[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public parkinginfoItem[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class parkinginfoItem {
    
    private string lOTField;
    
    private string cOUNT_AREA_IDField;
    
    private string cOUNT_AREA_DATEField;
    
    private string cOUNT_AREA_NAMEField;
    
    private string sPACESField;
    
    private string vEHICLESField;
    
    private string cAPACITYField;
    
    private string pERCENT_FULLField;
    
    private string tIME_TO_FULLField;
    
    private string percent_RampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LOT {
        get {
            return this.lOTField;
        }
        set {
            this.lOTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COUNT_AREA_ID {
        get {
            return this.cOUNT_AREA_IDField;
        }
        set {
            this.cOUNT_AREA_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COUNT_AREA_DATE {
        get {
            return this.cOUNT_AREA_DATEField;
        }
        set {
            this.cOUNT_AREA_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COUNT_AREA_NAME {
        get {
            return this.cOUNT_AREA_NAMEField;
        }
        set {
            this.cOUNT_AREA_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SPACES {
        get {
            return this.sPACESField;
        }
        set {
            this.sPACESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VEHICLES {
        get {
            return this.vEHICLESField;
        }
        set {
            this.vEHICLESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CAPACITY {
        get {
            return this.cAPACITYField;
        }
        set {
            this.cAPACITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PERCENT_FULL {
        get {
            return this.pERCENT_FULLField;
        }
        set {
            this.pERCENT_FULLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TIME_TO_FULL {
        get {
            return this.tIME_TO_FULLField;
        }
        set {
            this.tIME_TO_FULLField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Percent_Ramp {
        get {
            return this.percent_RampField;
        }
        set {
            this.percent_RampField = value;
        }
    }
}
